name: Python CI with 3.13

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python 3.13 manually
        run: |
          sudo apt update
          sudo apt install -y wget build-essential libssl-dev zlib1g-dev \
                              libncurses5-dev libncursesw5-dev libreadline-dev \
                              libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev \
                              libexpat1-dev liblzma-dev tk-dev libffi-dev uuid-dev

          wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0.tgz
          tar -xf Python-3.13.0.tgz
          cd Python-3.13.0
          ./configure --enable-optimizations
          make -j$(nproc)
          sudo make altinstall

          python3.13 --version

      - name: Install dependencies
        run: |
          python3.13 -m pip install --upgrade pip
          python3.13 -m pip install pytest

      - name: Run tests
        run: |
          python3.13 -m pytest
