name: Python CI with 3.13 (Custom)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python 3.13 (from source)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev zlib1g-dev \
            libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev \
            libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev tk-dev wget
          wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0a5.tgz
          tar xvf Python-3.13.0a5.tgz
          cd Python-3.13.0a5
          ./configure --enable-optimizations
          make -j$(nproc)
          sudo make altinstall
          python3.13 --version

      - name: Install dependencies
        run: |
          python3.13 -m pip install --upgrade pip
          python3.13 -m pip install pytest

      - name: Run YOUR test cases (not Python's)
        run: |
          python3.13 -m pytest
